apiVersion: v1
kind: Service
metadata:
  namespace: elasticsearch
  name: apm-server
  labels:
    component: apm-server
spec:
  selector:
    component: apm-server
  ports:
  - name: http
    port: 8200
