apiVersion: v1
kind: Service
metadata:
  namespace: elasticsearch
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  selector:
    component: elasticsearch
  ports:
  - name: http
    port: 9200
    nodePort: 31001
  type: "NodePort"
