apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    component: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      # See also: https://github.com/elastic/helm-charts/issues/137
      - name: dir-permissions
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
        command:
          - sh
          - -c
          - |
            chown -R 1000:1000 /data
        volumeMounts:
          - name: es-data
            mountPath: /data
      containers:
      - name: es-client
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ES_JAVA_OPTS
          value: -Xms4096m -Xmx8216m
        - name: NETWORK_HOST
          value: _site_,_lo_
        - name: NODE_NAME
          value: ""
        - name: ES_TMPDIR
          value: /tmp
        resources:
          limits:
            cpu: 1000m
            memory: 10Gi
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: http
        volumeMounts:
          - name: config-elasticsearch
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
          - name: config-es-log4j
            mountPath: /usr/share/elasticsearch/config/log4j2.properties
            subPath: log4j2.properties
          - name: es-data
            mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: config-elasticsearch
        configMap:
          name: es-configmap
      - name: config-es-log4j
        configMap:
          name: es-configmap
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 12Gi

