apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: elasticsearch
  name: kibana
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.3.1
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch.elasticsearch:9200
        - name: SERVER_HOST
          value: 0.0.0.0
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 500m
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                http () {
                    local path="${1}"
                    set -- -XGET -s --fail
                    if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
                      set -- "$@" -u "${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
                    fi
                    curl -k "$@" "http://localhost:5601${path}"
                }
                http "/app/kibana"
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 3
          failureThreshold: 3
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/kibana/config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 1000
      schedulerName: default-scheduler
      volumes:
      - name: config-volume
        configMap:
          name: es-configmap
          items:
            - key: kibana.yml
              path: kibana.yml
