apiVersion: v1
kind: Service
metadata:
  namespace: elasticsearch
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 5601
    targetPort: http
    nodePort: 31000
  type: "NodePort"
